spring.application.name=tp-hr-backend
spring.profiles.active=local

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

jwt.expiration-ms=3600000

server.port=8080
